name: Build Plugin

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master (0.5.x)
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.0.x

    - name: Build
      run: bash ./build-plugin.sh

    - name: Remove PDB files
      run: |
        find ./build -name "*.pdb" -type f -delete

    - uses: actions/upload-artifact@main
      with:
        name: "Wheel-Addon"
        path: |
          ./build/plugin/Wheel-Addon.zip
          !./build/*.pdb